language: go
sudo: false
go:
- 1.x
install:
- go get -u -v ./...
- GOOS=windows GOARCH=amd64 go get -u -v github.com/StackExchange/wmi
- GOOS=windows GOARCH=amd64 go get -u -v github.com/shirou/w32